#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错 
spring: 
  profiles: 
    active: dev

emp:
  name: zhangsan123
    
    
# 激活开发环境配置 
--- 
server:
  port: 8001


spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-config123 #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
mybatis:
  type-aliases-package: com.buba.pojo
  configuration: #开启驼峰命名
    map-underscore-to-camel-case: true

eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true # 服务发现开关
    serviceUrl: # 客户端注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://www.eureka6001.com:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了，相同的id会被eureka认为是同一个实例
    prefer-ip-address: true
    
# 激活生产环境配置 
--- 
server:
  port: 8001

spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product-config #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
mybatis:
  type-aliases-package: com.buba.pojo
  configuration: #开启驼峰命名
    map-underscore-to-camel-case: true

eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true # 服务发现开关
    serviceUrl: # 客户端注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://www.eureka6001.com:6001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了，相同的id会被eureka认为是同一个实例
    prefer-ip-address: true



